environment:
  nodejs_version: "10"

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i
  - npm i -g pkg
  - pkg -t win-%PLATFORM% xnbcli.js
  - cp node_modules/lz4/build/Release/lz4.node .
  - cp node_modules/lz4/build/Release/xxhash.node .
  - 7z a xnbcli-windows-%PLATFORM%.zip xnbcli.exe lz4.node xxhash.node packed unpacked unpack.bat pack.bat

artifacts:
  - path: xnbcli-windows-%PLATFORM%.zip
    name: xnbcli-windows

build: off

deploy:
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: non+6EH5t/R9Br3PFWpBkm5pFKV11VqNfAcRmqENsNPk8q5pIAHiuWR/GiMH3epz
  artifact: xnbcli-windows-%PLATFORM%.zip
  on:
    branch: master
    appveyor_repo_tag: true
